name = "Wipack"
author = "Ozoku"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f12322fe1a9109b304e33ced4d16873a84d253af20b80a239bcb2d4c1a89e2ea"

[versions]
forge = "36.2.34"
minecraft = "1.16.5"

[options]
acceptable-game-versions = ["1.16.4"]
