name = "Wipack"
author = "Ozoku"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5cb979e1d2b56f0b6b896578888f450da2c24729908b0fada7a57e8383042962"

[versions]
forge = "36.2.34"
minecraft = "1.16.5"

[options]
acceptable-game-versions = ["1.16.4"]
