name = "Wipack"
author = "Ozoku"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4e8513c80f993243de7b5c10578c06792fd5fee547cafcf53a67fd2792a33f23"

[versions]
forge = "36.2.34"
minecraft = "1.16.5"

[options]
acceptable-game-versions = ["1.16.4"]
