name = "Wipack"
author = "Ozoku"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7a61622ffc59c8dc1864e12987aaa91b884ac53dbaaeef7cdc7fb5b900497803"

[versions]
forge = "36.2.34"
minecraft = "1.16.5"

[options]
acceptable-game-versions = ["1.16.4"]
