name = "Wipack"
author = "Ozoku"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4548c7e835adb0d667eadfe094dd594094545e35623a36d60d1b880b3141a999"

[versions]
forge = "36.2.34"
minecraft = "1.16.5"

[options]
acceptable-game-versions = ["1.16.4"]
