
#Settings for stick crafting
[sticks]
	RemoveSticksFromPlanksRecipes = true

#Settings for rock and ore rock drops
[rocks]
	Enable = false
	ReplaceStoneDrops = false
	ReplaceIronOreDrops = false
	ReplaceGoldOreDrops = false
	ReplaceCopperOreDrops = false
	ReplaceLeadOreDrops = false
	ReplaceSilverOreDrops = false
	ReplaceAluminumOreDrops = false
	ReplaceTinOreDrops = false
	ReplacePoorOreDrops = false

#Settings for recipes
[recipes]
	CobbleRequiresClay = false

#Settings for the drying rack block
[drying_rack]
	EnableMeatRotting = true
	EnableRottenDrying = true
	EnableJerky = true
	EnableMeatDrying = true
	EnableLeatherTanning = true
	EnableSaddleCrafting = false

#Settings for the dough/bread replacements
[bread]
	Enable = false
	RemoveVanillaBread = false

#Settings for the chopping block
[chopping]
	#If enabled, the vanilla planks recipes will be disabled, using the log to craft choppingblock instead.
	#If disabled, the chopping block uses an alternate recipe, instead of using a single log as an input.
	ReplacePlanksRecipes = true

#Settings for the fibre collection
[fibres]
	DropStringFromSheep = false
	EnableStringCrafting = true
