name = "Abundance"
filename = "Abundance-1.16.5-1.0.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3250/108/Abundance-1.16.5-1.0.5.jar"
hash-format = "sha1"
hash = "320a8cd0eea1e1d5cba6c8a68edc7f88f119a684"

[update]
[update.curseforge]
file-id = 3250108
project-id = 452345
