name = "Advanced Peripherals"
filename = "advancedperipherals-1.16.5-0.7.8r.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3784/458/advancedperipherals-1.16.5-0.7.8r.jar"
hash-format = "sha1"
hash = "3525d1de7ea24f0c52fee28fe144761ac4d6a1ad"

[update]
[update.curseforge]
file-id = 3784458
project-id = 431725
