name = "Alex's Delight"
filename = "Alex's Delight 1.1.3 - Forge 1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3600/931/Alex%27s%20Delight%201.1.3%20-%20Forge%201.16.5.jar"
hash-format = "sha1"
hash = "a5db51e7f6a2ae23394cd6fe5f955d577591ba77"

[update]
[update.curseforge]
file-id = 3600931
project-id = 556448
