name = "Allurement"
filename = "allurement-1.16.5-1.2.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3520/927/allurement-1.16.5-1.2.1.jar"
hash-format = "sha1"
hash = "97ade0021b37e2f9397d5678cd21279c69ac2ec9"

[update]
[update.curseforge]
file-id = 3520927
project-id = 438003
