name = "Armor Toughness Bar"
filename = "toughnessbar-6.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3145/252/toughnessbar-6.1.jar"
hash-format = "sha1"
hash = "bf6c425dfe125245a7db0433c42062e96956531d"

[update]
[update.curseforge]
file-id = 3145252
project-id = 313816
