name = "Autumnity"
filename = "autumnity-1.16.5-2.1.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3553/317/autumnity-1.16.5-2.1.2.jar"
hash-format = "sha1"
hash = "20a72125b64df05b90aa5378a2b43bcebc5be386"

[update]
[update.curseforge]
file-id = 3553317
project-id = 365045
