name = "Balanced Flight (Angel Ring)"
filename = "balancedflight-mc1.16.5_v1.3.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3601/803/balancedflight-mc1.16.5_v1.3.0.jar"
hash-format = "sha1"
hash = "4f85894d34fa59cc24de2085f9f61a34f0292a23"

[update]
[update.curseforge]
file-id = 3601803
project-id = 538560
