name = "Balanced Enchanting"
filename = "balancedenchanting-1.16.2-1.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3636/34/balancedenchanting-1.16.2-1.1.jar"
hash-format = "sha1"
hash = "d60a0c757d3be1b671fa6bcfbba0d7a0838d84a2"

[update]
[update.curseforge]
file-id = 3636034
project-id = 399246
