name = "Bamboo Blocks"
filename = "bamboo_blocks-1.16.5-3.0.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3549/78/bamboo_blocks-1.16.5-3.0.1.jar"
hash-format = "sha1"
hash = "c927f0b5adaa665625de41cdb81905e6681752d1"

[update]
[update.curseforge]
file-id = 3549078
project-id = 348215
