name = "Bedspreads (Forge)"
filename = "bedspreads-forge-1.16.5-5.1.0.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3474/528/bedspreads-forge-1.16.5-5.1.0.3.jar"
hash-format = "sha1"
hash = "53963289455ed9f2a3951d5c764707e4e9782408"

[update]
[update.curseforge]
file-id = 3474528
project-id = 308653
