name = "Berry Good"
filename = "berry_good-1.16.5-4.1.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3549/57/berry_good-1.16.5-4.1.2.jar"
hash-format = "sha1"
hash = "db21aa63d0d032da5d5c49b210da4ed193d3aebd"

[update]
[update.curseforge]
file-id = 3549057
project-id = 355589
