name = "Better Badlands"
filename = "Better-Badlands-1.16.5-2.0.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3195/284/Better-Badlands-1.16.5-2.0.3.jar"
hash-format = "sha1"
hash = "11580c0eb9b51dee312983037dcfced5f5e55a28"

[update]
[update.curseforge]
file-id = 3195284
project-id = 421763
