name = "Better Burning"
filename = "BetterBurning-1.16.5-6.0.8.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3732/288/BetterBurning-1.16.5-6.0.8.jar"
hash-format = "sha1"
hash = "6e45edd8bd76d527c944d7e91bf93ef677d36602"

[update]
[update.curseforge]
file-id = 3732288
project-id = 353434
