name = "Big Brain"
filename = "bigbrain-1.2.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3328/916/bigbrain-1.2.4.jar"
hash-format = "sha1"
hash = "1885ad3bb1e3b07bc4db59e12e655729e3f5177c"

[update]
[update.curseforge]
file-id = 3328916
project-id = 421179
