name = "BlockCarpentry"
filename = "blockcarpentry-1.16-0.4.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3441/935/blockcarpentry-1.16-0.4.0.jar"
hash-format = "sha1"
hash = "6af772fe5abae7f67f854a0e191b9bdcf0b0b8ba"

[update]
[update.curseforge]
file-id = 3441935
project-id = 401658
