name = "Blood Magic "
filename = "BloodMagic-1.16.4-3.1.10-31.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "1e0fe029297c35926cbd8df0f15ff1c6ea3cbe73"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3796186
project-id = 224791
