name = "Borealis"
filename = "Borealis-1.2.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3649/462/Borealis-1.2.2.jar"
hash-format = "sha1"
hash = "01e08775100441bc4823f22e3b41a0f42c4fd320"

[update]
[update.curseforge]
file-id = 3649462
project-id = 443070
