name = "Botanical Machinery"
filename = "botanicalmachinery-1.16.4-0.4.6.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3672/479/botanicalmachinery-1.16.4-0.4.6.jar"
hash-format = "sha1"
hash = "cfa71d356df0421d36540e1bc1de2ebab159133b"

[update]
[update.curseforge]
file-id = 3672479
project-id = 395617
