name = "Bountiful (Forge)"
filename = "Bountiful-1.16.4-3.3.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3239/647/Bountiful-1.16.4-3.3.1.jar"
hash-format = "sha1"
hash = "ec7709bb36416e9fcb1a886d899b159e27d4d14a"

[update]
[update.curseforge]
file-id = 3239647
project-id = 309516
