name = "Buzzier Bees"
filename = "buzzier_bees-1.16.5-3.0.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3561/118/buzzier_bees-1.16.5-3.0.3.jar"
hash-format = "sha1"
hash = "19c5755eb497c5224008e9b6d35669576bd73ade"

[update]
[update.curseforge]
file-id = 3561118
project-id = 355458
