name = "Cable Tiers"
filename = "cabletiers-1.16.5-0.5442.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "441afa822c422caeb8d0754e281be8971511f51a"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3787208
project-id = 454382
