name = "Cat Jammies"
filename = "catjammies-1.1.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3252/734/catjammies-1.1.0.jar"
hash-format = "sha1"
hash = "63679578f39a34c07a607c6468a6862074f3cb93"

[update]
[update.curseforge]
file-id = 3252734
project-id = 430906
