name = "Catalogue"
filename = "catalogue-1.6.1-1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3780/550/catalogue-1.6.1-1.16.5.jar"
hash-format = "sha1"
hash = "1f043d42bd191d4701b6b58e47ccd247daacd81c"

[update]
[update.curseforge]
file-id = 3780550
project-id = 459701
