name = "Charmonium Reforged"
filename = "charmonium-forge-1.16.5-2.3.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3214/653/charmonium-forge-1.16.5-2.3.2.jar"
hash-format = "sha1"
hash = "c63193bf799ddbbff08379b9014331b0153263b2"

[update]
[update.curseforge]
file-id = 3214653
project-id = 431587
