name = "Charcoal Pit"
filename = "CharcoalPit-1.16.5-2.13.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3304/824/CharcoalPit%5B1.16.5%5D-2.13.jar"
hash-format = "sha1"
hash = "f28d95a570dcb7390a76e1e898a50e1c056d2bc2"

[update]
[update.curseforge]
file-id = 3304824
project-id = 264111
