name = "Chicken's Compat"
filename = "muchmoremodcompat-1.0.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3419/826/muchmoremodcompat-1.0.0.jar"
hash-format = "sha1"
hash = "a0f0e077802d3b546fbad8ed6f474c41522bf476"

[update]
[update.curseforge]
file-id = 3419826
project-id = 513731
