name = "Click Machine"
filename = "ClickMachine-1.16.5-4.5.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3490/353/ClickMachine-1.16.5-4.5.0.jar"
hash-format = "sha1"
hash = "bfa4b0abd2575ccef30989afd053e95c4c2466fe"

[update]
[update.curseforge]
file-id = 3490353
project-id = 298275
