name = "Clickable advancements[Forge/Fabric]"
filename = "clickadv-2.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3649/28/clickadv-2.3.jar"
hash-format = "sha1"
hash = "b18b89bc323cc56feebb6bf0dd594a5fbbce1d4e"

[update]
[update.curseforge]
file-id = 3649028
project-id = 511733
