name = "Shulker's Faithful Factories (Previously Cobbler)"
filename = "cobbler-1.6.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3132/33/cobbler-1.6.1.jar"
hash-format = "sha1"
hash = "e558931275d7cbba9998fde8449a22d64908a26e"

[update]
[update.curseforge]
file-id = 3132033
project-id = 380136
