name = "Cookielicious"
filename = "cookielicious-1.16.5-1.4.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3491/52/cookielicious-1.16.5-1.4.3.jar"
hash-format = "sha1"
hash = "bfead3921e9eb5569a36d3a8acd468b5387f58c0"

[update]
[update.curseforge]
file-id = 3491052
project-id = 409577
