name = "Crash Utilities"
filename = "crashutilities-3.13.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3584/716/crashutilities-3.13.jar"
hash-format = "sha1"
hash = "b33300f1dd9d839482df7a3db29539b1d1aedcca"

[update]
[update.curseforge]
file-id = 3584716
project-id = 371813
