name = "Create: Alloyed"
filename = "alloyed-1.16.5-v0.3a.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3738/19/alloyed-1.16.5-v0.3a.jar"
hash-format = "sha1"
hash = "03a30a129d8c00e0fc5c05294a5e12a58bf10ae2"

[update]
[update.curseforge]
file-id = 3738019
project-id = 564792
