name = "Custom Machinery"
filename = "custommachinery-1.16.5-0.5.8f.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "2678d2f1ad602d33ef914fbd28a9b1bfa8b96c3a"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3787990
project-id = 457017
