name = "Cyclops Core"
filename = "CyclopsCore-1.16.5-1.12.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3756/546/CyclopsCore-1.16.5-1.12.3.jar"
hash-format = "sha1"
hash = "538ca01b7d472287d79d16e046493aedc4a30153"

[update]
[update.curseforge]
file-id = 3756546
project-id = 232758
