name = "Dark Paintings"
filename = "DarkPaintings-1.16.5-6.0.11.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3732/278/DarkPaintings-1.16.5-6.0.11.jar"
hash-format = "sha1"
hash = "58aaebf575581f089d806fbc7869d07506b44406"

[update]
[update.curseforge]
file-id = 3732278
project-id = 377281
