name = "Dash"
filename = "dash-1.16.4-1.0.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3100/345/dash-1.16.4-1.0.1.jar"
hash-format = "sha1"
hash = "d53134baf127d01dfe9301c6041e51a47e534120"

[update]
[update.curseforge]
file-id = 3100345
project-id = 370782
