name = "DeLogger"
filename = "DeLogger-3.0.4-build.20+mc1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3559/956/DeLogger-3.0.4-build.20+mc1.16.5.jar"
hash-format = "sha1"
hash = "75be3aad1c30fb8809d60b08823a4252561b31d3"

[update]
[update.curseforge]
file-id = 3559956
project-id = 413477
