name = "Desolation (Forge)"
filename = "Desolation 1.1.2 1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3599/412/Desolation%201.1.2%201.16.5.jar"
hash-format = "sha1"
hash = "df0ed315a74435b27b98c8b285d0afd0745b42f8"

[update]
[update.curseforge]
file-id = 3599412
project-id = 445926
