name = "Diet (Forge)"
filename = "diet-forge-1.16.5-1.0.4.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3758/888/diet-forge-1.16.5-1.0.4.0.jar"
hash-format = "sha1"
hash = "59decb3011cc54fae867f52025960d626be50642"

[update]
[update.curseforge]
file-id = 3758888
project-id = 443570
