name = "Differentiate"
filename = "differentiate-1.16.5-0.5.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3397/138/differentiate-1.16.5-0.5.3.jar"
hash-format = "sha1"
hash = "f488424c8c868fb4988c70059572a23625a35fdf"

[update]
[update.curseforge]
file-id = 3397138
project-id = 450748
