name = "Draconic Evolution"
filename = "Draconic-Evolution-1.16.5-3.0.25.456-universal.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3779/345/Draconic-Evolution-1.16.5-3.0.25.456-universal.jar"
hash-format = "sha1"
hash = "b9f3bc349d5579adecbfea66a41da0e9c69f1a49"

[update]
[update.curseforge]
file-id = 3779345
project-id = 223565
