name = "Drawers Tooltip"
filename = "DrawersTooltip-1.16.2-2.1.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3491/850/DrawersTooltip-1.16.2-2.1.1.jar"
hash-format = "sha1"
hash = "c0cc5721963337e304193b6e8e964c79ea689c20"

[update]
[update.curseforge]
file-id = 3491850
project-id = 381605
