name = "Dungeons Plus"
filename = "dungeons_plus-1.16.5-1.1.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3318/948/dungeons_plus-1.16.5-1.1.5.jar"
hash-format = "sha1"
hash = "700cde5afe55963df9e0eb70d6ac85418e1137d4"

[update]
[update.curseforge]
file-id = 3318948
project-id = 377794
