name = "Eidolon"
filename = "eidolon-0.2.7.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3157/832/eidolon-0.2.7.jar"
hash-format = "sha1"
hash = "8dc85b50a88b9b3ef96bb934a6aca0d4f4388a80"

[update]
[update.curseforge]
file-id = 3157832
project-id = 429625
