name = "Engineer's Decor"
filename = "engineersdecor-1.16.5-1.1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3773/570/engineersdecor-1.16.5-1.1.18.jar"
hash-format = "sha1"
hash = "71bb27f13138d4ec4aea2b8c9fc9a263c76b669c"

[update]
[update.curseforge]
file-id = 3773570
project-id = 313866
