name = "Enhanced Mushrooms"
filename = "Enhanced-Mushrooms-1.16.5-3.0.9.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3353/212/Enhanced-Mushrooms-1.16.5-3.0.9.jar"
hash-format = "sha1"
hash = "621826bda63cb0401969111b564998e51afb7e3a"

[update]
[update.curseforge]
file-id = 3353212
project-id = 383725
