name = "Extended Crafting"
filename = "ExtendedCrafting-1.16.5-3.1.11.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3591/820/ExtendedCrafting-1.16.5-3.1.11.jar"
hash-format = "sha1"
hash = "0ac884d251e4d0d78bfda21301d046c34e2a4bd2"

[update]
[update.curseforge]
file-id = 3591820
project-id = 268387
