name = "FindMe"
filename = "findme-1.16.3-2.2.1.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3586/951/findme-1.16.3-2.2.1.0.jar"
hash-format = "sha1"
hash = "13b54107e3804f424deeceb69b6754fc65267b23"

[update]
[update.curseforge]
file-id = 3586951
project-id = 291936
