name = "Framed Compacting Drawers"
filename = "framedcompactdrawers-1.16-2.2.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3487/197/framedcompactdrawers-1.16-2.2.1.jar"
hash-format = "sha1"
hash = "d1ff92cf6e0976d2f4fe43fc7c805250c6cf3ac4"

[update]
[update.curseforge]
file-id = 3487197
project-id = 376351
