name = "Frozen Up"
filename = "frozenup-1.0.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3200/324/frozenup-1.0.1.jar"
hash-format = "sha1"
hash = "98a6dd4bd843982af1bd30e3c80449f75be7d739"

[update]
[update.curseforge]
file-id = 3200324
project-id = 430652
