name = "Iceberg"
filename = "Iceberg-1.16.5-1.0.38.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3609/915/Iceberg-1.16.5-1.0.38.jar"
hash-format = "sha1"
hash = "9cad4ca96579299f1e15665da3d0231c04d3b462"

[update]
[update.curseforge]
file-id = 3609915
project-id = 520110
