name = "Illagers+"
filename = "illagers_plus-1.16.4v1.7.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3507/42/illagers_plus-1.16.4v1.7.2.jar"
hash-format = "sha1"
hash = "0381286f4d0833ab9b5dff34fc9e7bc2fd48b316"

[update]
[update.curseforge]
file-id = 3507042
project-id = 325851
