name = "In Control!"
filename = "incontrol-1.16-5.2.7.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "5c72ed8586d8c698c4652e4735a37538ab02b528"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3798761
project-id = 257356
