name = "Industrial Foregoing"
filename = "industrial-foregoing-1.16.5-3.2.14.6-14.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3446/262/industrial-foregoing-1.16.5-3.2.14.6-14.jar"
hash-format = "sha1"
hash = "44c0cb35b936b4d852ac8f242399251207ba2c98"

[update]
[update.curseforge]
file-id = 3446262
project-id = 266515
