name = "Integrated NBT"
filename = "integratednbt-1.16.4-1.4.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3228/821/integratednbt-1.16.4-1.4.2.jar"
hash-format = "sha1"
hash = "7f22369b8d62bf0654b64957bbd6764508cfac52"

[update]
[update.curseforge]
file-id = 3228821
project-id = 380998
