name = "Integrated Dynamics"
filename = "IntegratedDynamics-1.16.5-1.10.10.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3782/101/IntegratedDynamics-1.16.5-1.10.10.jar"
hash-format = "sha1"
hash = "b521b6ef35713aa811445ffd02d66c674e3011dd"

[update]
[update.curseforge]
file-id = 3782101
project-id = 236307
