name = "Integrated Additions"
filename = "integratedadditions-1.1.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3530/275/integratedadditions-1.1.4.jar"
hash-format = "sha1"
hash = "34afe52582693d5261c4075259544a20380d9733"

[update]
[update.curseforge]
file-id = 3530275
project-id = 496091
