name = "Item Filters"
filename = "item-filters-forge-1605.2.5-build.9.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3376/819/item-filters-forge-1605.2.5-build.9.jar"
hash-format = "sha1"
hash = "52c14355c8e416d30f92eb2a2544f397f4693c34"

[update]
[update.curseforge]
file-id = 3376819
project-id = 309674
