name = "JourneyMap Integration"
filename = "jmi-1.16.5-0.8.1-47.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3696/645/jmi-1.16.5-0.8.1-47.jar"
hash-format = "sha1"
hash = "1abffab7b4fe54a46afb03fb0f2bf917035479e4"

[update]
[update.curseforge]
file-id = 3696645
project-id = 525447
