name = "JourneyMap"
filename = "journeymap-1.16.5-5.8.5.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "8571fa856eb5ec940d6a829510e741b180ce2e5b"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3798644
project-id = 32274
