name = "Kotlin for Forge"
filename = "kotlinforforge-1.17.0-obf.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3675/495/kotlinforforge-1.17.0-obf.jar"
hash-format = "sha1"
hash = "b9df7eef9f3c9bf77f19b15879d123de650a85e3"

[update]
[update.curseforge]
file-id = 3675495
project-id = 351264
