name = "KubeJS Borealis"
filename = "KubeJSBorealis-1.1.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3649/464/KubeJSBorealis-1.1.0.jar"
hash-format = "sha1"
hash = "29e3d1fd29fecf928f9a0bf88b42b936d5d7b52a"

[update]
[update.curseforge]
file-id = 3649464
project-id = 445077
