name = "Lepton (Forge)"
filename = "lepton-1.16.5-1.3.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3433/589/lepton-1.16.5-1.3.2.jar"
hash-format = "sha1"
hash = "8b554f0d33a1c10930a8252f3ce1ac319c17cbdc"

[update]
[update.curseforge]
file-id = 3433589
project-id = 407384
