name = "Lootr (Forge)"
filename = "lootr-1.16.5-0.1.12.42.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3736/640/lootr-1.16.5-0.1.12.42.jar"
hash-format = "sha1"
hash = "a8a8b84b33b3ca11f83653d31f746d14b8bc1589"

[update]
[update.curseforge]
file-id = 3736640
project-id = 361276
