name = "More Minecarts and Rails"
filename = "moreminecarts-1.3.16.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3775/668/moreminecarts-1.3.16.jar"
hash-format = "sha1"
hash = "057bd8ac418b27356dd06e13483cf13009695bef"

[update]
[update.curseforge]
file-id = 3775668
project-id = 440845
