name = "Music Duration Reducer"
filename = "musicdr-forge-1.2.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3211/258/musicdr-forge-1.2.0.jar"
hash-format = "sha1"
hash = "2eeffbfc864b5ecd0b7ca06743669045cdbdbab7"

[update]
[update.curseforge]
file-id = 3211258
project-id = 400131
