name = "Neapolitan"
filename = "neapolitan-1.16.5-2.2.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3567/243/neapolitan-1.16.5-2.2.1.jar"
hash-format = "sha1"
hash = "9672280f3c383b773857491f41639cdca5e8707e"

[update]
[update.curseforge]
file-id = 3567243
project-id = 382016
