name = "Neat"
filename = "Neat 1.7-27.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3182/258/Neat%201.7-27.jar"
hash-format = "sha1"
hash = "c11c05f861f274d1750859c27f77c2d5cca8574f"

[update]
[update.curseforge]
file-id = 3182258
project-id = 238372
