name = "Neko's Enchanted Books"
filename = "NekosEnchantedBooks-1.16-1.7.0.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3780/206/NekosEnchantedBooks-1.16-1.7.0.jar"
hash-format = "sha1"
hash = "58b6f88a000a1d861d2b7b23701c648a944fd827"

[update]
[update.curseforge]
file-id = 3780206
project-id = 441114
