name = "No Night Vision Flashing"
filename = "no_nv_flash-1.16.5-1.3.0.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3527/430/no_nv_flash-1.16.5-1.3.0.1.jar"
hash-format = "sha1"
hash = "8635070aa476c78b30006cc135b6aed2860072c4"

[update]
[update.curseforge]
file-id = 3527430
project-id = 291926
