name = "No Tree Punching"
filename = "notreepunching-forge-1.16.5-4.3.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3590/179/notreepunching-forge-1.16.5-4.3.0.jar"
hash-format = "sha1"
hash = "b9ef5c2288632446ae1ab277a3b15d90fd8e34ae"

[update]
[update.curseforge]
file-id = 3590179
project-id = 289043
