name = "Not Enough Animations"
filename = "notenoughanimations-1.2.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3296/39/notenoughanimations-1.2.4.jar"
hash-format = "sha1"
hash = "cac24f363376be715b37b7b363048a32186b7f1d"

[update]
[update.curseforge]
file-id = 3296039
project-id = 433760
