name = "Notes"
filename = "Notes-1.16.5-1.2.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3191/743/Notes-1.16.5-1.2.3.jar"
hash-format = "sha1"
hash = "3acf878f87d0b821da69583e1caef5fe75e043a9"

[update]
[update.curseforge]
file-id = 3191743
project-id = 256087
