name = "Overloaded Armor Bar"
filename = "overloadedarmorbar-5.1.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3055/679/overloadedarmorbar-5.1.0.jar"
hash-format = "sha1"
hash = "7a1cd685595816ddf3c598ab6c75c14864c0825a"

[update]
[update.curseforge]
file-id = 3055679
project-id = 314002
