name = "Peculiars"
filename = "peculiars-1.16.5-2.0.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3559/671/peculiars-1.16.5-2.0.1.jar"
hash-format = "sha1"
hash = "42a755b53527c9e5e892db76c29ee247a37fadf5"

[update]
[update.curseforge]
file-id = 3559671
project-id = 418551
