name = "Personality"
filename = "personality-1.16.5-1.0.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3549/549/personality-1.16.5-1.0.3.jar"
hash-format = "sha1"
hash = "96be05436ad2441480871e5c2cf2dbf0ce12de30"

[update]
[update.curseforge]
file-id = 3549549
project-id = 415974
