name = "Phi (Psi addon)"
filename = "Phi-1.16-2.6.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3771/904/Phi-1.16-2.6.jar"
hash-format = "sha1"
hash = "5b81521146426b7ca2ee0795ba4fbce5b749dd21"

[update]
[update.curseforge]
file-id = 3771904
project-id = 476728
