name = "Pipez"
filename = "pipez-1.16.5-1.2.17.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3760/254/pipez-1.16.5-1.2.17.jar"
hash-format = "sha1"
hash = "b0c6cc4ccd64585383924f61c5e9035ccae6136b"

[update]
[update.curseforge]
file-id = 3760254
project-id = 443900
