name = "PneumaticCraft: Repressurized"
filename = "pneumaticcraft-repressurized-1.16.5-2.15.8-324.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "9e611ca2777957cc506ecf3cbc9af6cc543d3732"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3797021
project-id = 281849
