name = "Pollen"
filename = "pollen-forge-1.4.1+1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3778/222/pollen-forge-1.4.1+1.16.5.jar"
hash-format = "sha1"
hash = "15af174a92a0b91a2b08a768db33d23763abb14b"

[update]
[update.curseforge]
file-id = 3778222
project-id = 544350
