name = "Potion Descriptions (Forge)"
filename = "potiondescriptions-1.16.5-1.5.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3302/804/potiondescriptions-1.16.5-1.5.3.jar"
hash-format = "sha1"
hash = "787a1db921666f0b49be7389cc41a77edfa8fc2a"

[update]
[update.curseforge]
file-id = 3302804
project-id = 403303
