name = "Pretty Beaches"
filename = "PrettyBeaches_1.16.3-5.2.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3066/121/PrettyBeaches_1.16.3-5.2.0.jar"
hash-format = "sha1"
hash = "2c7f6116d7ee094ffe1f1e204c7fb7ca098ecc75"

[update]
[update.curseforge]
file-id = 3066121
project-id = 290659
