name = "Project Intelligence"
filename = "ProjectIntelligence-1.16.5-1.1.0.35-universal.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3682/621/ProjectIntelligence-1.16.5-1.1.0.35-universal.jar"
hash-format = "sha1"
hash = "73924a57b34614155af687e630432fb0f950e423"

[update]
[update.curseforge]
file-id = 3682621
project-id = 306028
