name = "Psi"
filename = "Psi 1.16-97.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3493/912/Psi%201.16-97.jar"
hash-format = "sha1"
hash = "27893311063e7aa462c99222a75ae3ede7846845"

[update]
[update.curseforge]
file-id = 3493912
project-id = 241665
