name = "Psionic Peripherals"
filename = "psipherals-1.4.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3404/863/psipherals-1.4.1.jar"
hash-format = "sha1"
hash = "60080a5d9d1cb09c27bc9ffd986d632155281087"

[update]
[update.curseforge]
file-id = 3404863
project-id = 324813
