name = "Puzzles Lib [Forge]"
filename = "PuzzlesLib-v1.0.15-1.16.5-Forge.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3517/499/PuzzlesLib-v1.0.15-1.16.5-Forge.jar"
hash-format = "sha1"
hash = "7094b4a86ce0d94ef1a7ea0935c6a9496564a17e"

[update]
[update.curseforge]
file-id = 3517499
project-id = 495476
