name = "Raven Coffee"
filename = "ravencoffee-1.16.5-alpha_rev2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3758/736/ravencoffee-1.16.5-alpha_rev2.jar"
hash-format = "sha1"
hash = "3ac3f8743c364b3e767ba710f406eb84f8a9d228"

[update]
[update.curseforge]
file-id = 3758736
project-id = 469185
