name = "Redstone Pen"
filename = "redstonepen-1.16.5-1.0.8-b3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3675/500/redstonepen-1.16.5-1.0.8-b3.jar"
hash-format = "sha1"
hash = "182d76323711e328a99ccc9d6cf0f0abe66df14e"

[update]
[update.curseforge]
file-id = 3675500
project-id = 461710
