name = "Save My Stronghold! (Forge)"
filename = "SaveMyStronghold-1.16.4-1.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3188/216/SaveMyStronghold-1.16.4-1.0.jar"
hash-format = "sha1"
hash = "e662cb4d4a046ee7c52b2ba72eef66f78daf3204"

[update]
[update.curseforge]
file-id = 3188216
project-id = 355248
