name = "Scuba Gear"
filename = "scuba-gear-1.16.5-1.0.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3243/305/scuba-gear-1.16.5-1.0.3.jar"
hash-format = "sha1"
hash = "d3cbb8a4935d23e78bc6332764f53f383dbf2a7b"

[update]
[update.curseforge]
file-id = 3243305
project-id = 399090
