name = "ServerConfig Updater"
filename = "serverconfigupdater-1.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3034/936/serverconfigupdater-1.3.jar"
hash-format = "sha1"
hash = "e653432fbbe97c8ba26a28138a0e61714863e262"

[update]
[update.curseforge]
file-id = 3034936
project-id = 365281
