name = "Sewing Kit"
filename = "SewingKit-1.16.5-1.3.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3202/871/SewingKit-1.16.5-1.3.1.jar"
hash-format = "sha1"
hash = "cedf7e848160632af7ea30415b0770f854cbec1d"

[update]
[update.curseforge]
file-id = 3202871
project-id = 411896
