name = "Shrines Structures"
filename = "Shrines-1.16.5-2.2.2.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "02bc674188992d7447d0c61291f5f2181ec018b6"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3801303
project-id = 418915
