name = "Shrines Structures"
filename = "Shrines-1.16.5-2.2.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3660/953/Shrines-1.16.5-2.2.1.jar"
hash-format = "sha1"
hash = "287de8c7df55675b6144d5ccbc8ff2ad02b33c08"

[update]
[update.curseforge]
file-id = 3660953
project-id = 418915
