name = "Simply Tea!"
filename = "simplytea-1.16.5-2.4.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3310/150/simplytea-1.16.5-2.4.0.jar"
hash-format = "sha1"
hash = "9d010decf9ecfff8f879547b2a28dce43b3ca6b0"

[update]
[update.curseforge]
file-id = 3310150
project-id = 268373
