name = "Smooth Boot (Forge)"
filename = "smoothboot-forge-1.16.4-1.2.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3224/252/smoothboot-forge-1.16.4-1.2.2.jar"
hash-format = "sha1"
hash = "483f6d696b5166fd0f3fbf6b2e8138bc39db2660"

[update]
[update.curseforge]
file-id = 3224252
project-id = 420913
