name = "Spawner Bug Fix"
filename = "SpawnerFix-1.16.2-1.0.0.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3161/147/SpawnerFix-1.16.2-1.0.0.2.jar"
hash-format = "sha1"
hash = "7afca46cda651407d537ab2b25b06d3320731b06"

[update]
[update.curseforge]
file-id = 3161147
project-id = 399022
