name = "Create: Steam Powered"
filename = "steampowered-1.16.5-1.2.0-hf1.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "387a30b85fe17f3f7cffe3282bc17b61d5044efa"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3801469
project-id = 534610
