name = "Storage Drawers"
filename = "StorageDrawers-1.16.3-8.5.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3776/277/StorageDrawers-1.16.3-8.5.2.jar"
hash-format = "sha1"
hash = "854514ef529e665b77632882f7274642f11517dd"

[update]
[update.curseforge]
file-id = 3776277
project-id = 223852
