name = "Structure Gel API"
filename = "structure_gel-1.16.5-1.7.8.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3498/310/structure_gel-1.16.5-1.7.8.jar"
hash-format = "sha1"
hash = "ee06be23ae3184d2a89ea70c8ab0f5c95118f07f"

[update]
[update.curseforge]
file-id = 3498310
project-id = 378802
