name = "Stylish Effects [Forge]"
filename = "StylishEffects-v1.2.1-1.16.5-Forge.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3583/492/StylishEffects-v1.2.1-1.16.5-Forge.jar"
hash-format = "sha1"
hash = "7d8db669b7a8650c5e40503cdfef905ffe6f1451"

[update]
[update.curseforge]
file-id = 3583492
project-id = 543661
