name = "Survivalist"
filename = "Survivalist-1.16.5-3.3.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3402/145/Survivalist-1.16.5-3.3.2.jar"
hash-format = "sha1"
hash = "3cd94416d220a12f4934d4902651b3d0fa77a2c5"

[update]
[update.curseforge]
file-id = 3402145
project-id = 242289
