name = "Tetranomicon"
filename = "tetranomicon-1.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3349/970/tetranomicon-1.3.jar"
hash-format = "sha1"
hash = "6950ff0508be28b13dc7c277326890f0ff4dd307"

[update]
[update.curseforge]
file-id = 3349970
project-id = 445385
