name = "The Conjurer"
filename = "the-conjurer-1.16.4-1.0.13.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3107/953/the-conjurer-1.16.4-1.0.13.jar"
hash-format = "sha1"
hash = "3dd29349f2190d2f5b40cebed4fa67f6bb716324"

[update]
[update.curseforge]
file-id = 3107953
project-id = 377798
