name = "The Irregular Chef! (A Farmer's Delight Add-on)"
filename = "irregularchef-1.16.5-1.0.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3411/810/irregularchef-1.16.5-1.0.1.jar"
hash-format = "sha1"
hash = "40b0a0d8a2d61ab961507d06dbf7ce8b50f18ee4"

[update]
[update.curseforge]
file-id = 3411810
project-id = 498222
