name = "TiCBC - Tinkers Better Compat"
filename = "bettercompat-0.4.2-1.16.5-36.2.34.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3777/762/bettercompat-0.4.2-1.16.5-36.2.34.jar"
hash-format = "sha1"
hash = "d4363deae969378076333faf6e5f9af032681f53"

[update]
[update.curseforge]
file-id = 3777762
project-id = 475145
