name = "Tinker's Planner"
filename = "tconplanner-1.16.5-1.1.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3523/698/tconplanner-1.16.5-1.1.1.jar"
hash-format = "sha1"
hash = "b66be19a6ed7e63928cb128bee974806b73f3d26"

[update]
[update.curseforge]
file-id = 3523698
project-id = 519973
