name = "Tool Belt"
filename = "ToolBelt-1.16.5-1.16.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3696/855/ToolBelt-1.16.5-1.16.2.jar"
hash-format = "sha1"
hash = "f3869b1a3aa4c7b7aff9f8064a8136c7aa0c0cc3"

[update]
[update.curseforge]
file-id = 3696855
project-id = 260262
