name = "Tool Stats"
filename = "ToolStats-1.16.5-6.0.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3732/280/ToolStats-1.16.5-6.0.5.jar"
hash-format = "sha1"
hash = "c563b7a2242726a4353c032ea45ee42f094ff233"

[update]
[update.curseforge]
file-id = 3732280
project-id = 377109
