name = "Trample Stopper"
filename = "TrampleStopper-2.6.1-build.22+mc1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3432/688/TrampleStopper-2.6.1-build.22+mc1.16.5.jar"
hash-format = "sha1"
hash = "91dff2405461b7103fb2bc9192a8cbe9555483d6"

[update]
[update.curseforge]
file-id = 3432688
project-id = 297028
