name = "TRansliterationLib"
filename = "TRansliterationLib-1.0.4.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3251/51/TRansliterationLib-1.0.4.jar"
hash-format = "sha1"
hash = "aff3715d0df300697760d9f6937bcec10a6bdbd0"

[update]
[update.curseforge]
file-id = 3251051
project-id = 441024
