name = "Void Totem (Forge)"
filename = "voidtotem-1.16.5-1.4.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3327/88/voidtotem-1.16.5-1.4.0.jar"
hash-format = "sha1"
hash = "22bfc9d20a52ae636cf42458cefb15fb44b44ddf"

[update]
[update.curseforge]
file-id = 3327088
project-id = 449655
