name = "When Dungeons Arise - Forge!"
filename = "DungeonsArise-1.16.5-2.1.49-beta.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3534/647/DungeonsArise-1.16.5-2.1.49-beta.jar"
hash-format = "sha1"
hash = "84ebbfa27c8b8b2f51171badf947e7e042a3f123"

[update]
[update.curseforge]
file-id = 3534647
project-id = 442508
